service: complete-example

plugins:
  - '@kitchenshelf/serverless-rspack'
  - serverless-offline

build:
  esbuild: false

custom:
  rspack:
    keepOutputDirectory: true
    sourcemap: 'source-map'
    stats: true
    esm: true
    doctor:
      enable: false
      outputDirectory: ./
    mode: production
    tsConfig: './tsconfig.json'
    externals:
      - '^@aws-sdk/.*$'
      - '^@smithy/.*$'
      - '^isin-validator$'
      - '^sharp$'
    scripts:
      - 'echo "First global script"'
      - 'echo "Last global script"'

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true

functions:
  App1:
    handler: app1.handler
    runtime: 'provided.al2023'
    rspack: true
  app2:
    handler: app2.lambda_handler
    runtime: python3.9
  app3:
    events:
      - http:
          method: get
          path: helloApp3
    handler: src/App3.handler
    runtime: nodejs20.x
    rspack:
      enable: true
      scripts:
        - 'echo "First function script"'
        - 'npx npm init -y && npm install --force --os=linux --cpu=x64 --include=optional sharp @img/sharp-linux-x64'
        - 'cp $KS_SERVICE_DIR/src/my-image.jpeg ./'
        - 'echo "Last function script"'
  app4:
    handler: src/app4.handler
  app5:
    handler: src/deeply/nested/somewhat/app5.handler
  app6:
    handler: src/deeply/nested/somewhat/app5.handler
    rspack: false
